// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module('walletApp', ['LocalStorageModule']);

  app.controller('walletController', [
    '$scope', 'localStorageService', function($scope, localStorageService) {
      var items;
      items = localStorageService.get('walletItems');
      console.log(items);
      $scope.items = items != null ? items : [];
      $scope.persist = function() {
        localStorageService.set('walletItems', $scope.items);
        return console.log($scope.items);
      };
      $scope.getTotal = function() {
        return _.reduce($scope.items, function(memo, item) {
          return memo + item.amount;
        }, 0);
      };
      $scope.addItem = function(amount) {
        $scope.items.push({
          date: new Date(),
          amount: amount
        });
        return $scope.persist();
      };
      $scope.resetItems = function() {
        $scope.items = [];
        return $scope.persist();
      };
      return $scope.$on('resetWallet', function(e, args) {
        return $scope.resetItems();
      });
    }
  ]);

  app.controller('menuController', [
    '$scope', function($scope) {
      return $scope.reset = function() {
        return $scope.$emit('resetWallet', {});
      };
    }
  ]);

}).call(this);
