// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module('walletApp', []);

  app.controller('walletController', [
    '$scope', function($scope) {
      $scope.items = [
        {
          date: new Date(2014, 9, 9, 10, 30, 0),
          amount: 10.50
        }, {
          date: new Date(2014, 9, 8, 11, 30, 0),
          amount: -6.23
        }
      ];
      $scope.getTotal = function() {
        return _.reduce($scope.items, function(memo, item) {
          return memo + item.amount;
        }, 0);
      };
      $scope.addItem = function(amount) {
        return $scope.items.push({
          date: new Date(),
          amount: amount
        });
      };
      $scope.resetItems = function() {
        return $scope.items = [];
      };
      return $scope.$on('resetWallet', function(e, args) {
        return $scope.resetItems();
      });
    }
  ]);

  app.controller('menuController', [
    '$scope', function($scope) {
      return $scope.reset = function() {
        return $scope.$emit('resetWallet', {});
      };
    }
  ]);

}).call(this);
